services:
  # Backend API Service (Free Tier)
  - type: web
    name: exportable-markdown-api
    runtime: node
    plan: free  # Explicitly use free tier
    rootDir: ./exportable-markdown-node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false # You'll set this in Render dashboard
      - key: CORS_ORIGIN
        sync: false # Will be set to your frontend URL
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable